# Sprint2_Part2_Colab(2)_데이터프레임 다루기

> 목표: 데이터프레임에 대한 기본적인 구조를 경험해보기  
> 내용: 데이터 확인 및 점검    

**데이터 정보 확인** shape, info(), describe()   
**결측치, 중복값 확인**  isnull, duplicated   
기본 인덱싱, 슬라이싱, 불리언 인덱싱

## 데이터 가져오기  
> 파일 경로를 입력하여 데이터를 손쉽게 가져올 수 있다.  
> 교안에서는 편의상 url로 대체하지만 colab에는 구글드라이브 마운트, 파일 업로드 등 다양한 방식이 있다.  


url로 데이터를 불러오고, 데이터 구조 및 정보, 수치정보를 확인해 본다.

![titanic](https://velog.velcdn.com/images/chaliechu117/post/020dcc3d-7cd6-43c3-b696-116c6ac593bd/image.jpg)

**해당 표는 편의를 위해 수기로 작성한 것이며, 일반적으로 칼럼 설명은 직접 찾아봐야 한다.**


| 컬럼명             | 의미    | 설명                  |
| --------------- | -------- | ------------------- |
| **PassengerId** | 승객 ID    | 각 승객을 구분하기 위한 고유 번호 |
| **Survived**    | 생존 여부    | 생존 = 1, 사망 = 0      |
| **Pclass**      | 객실 등급    | 1등석 / 2등석 / 3등석     |
| **Name**        | 이름       | 승객의 이름              |
| **Sex**         | 성별       | male / female       |
| **Age**         | 나이       | 승객의 나이      |
| **SibSp**       | 형제·배우자 수 | 함께 탑승한 형제자매 + 배우자 수 |
| **Parch**       | 부모·자녀 수  | 함께 탑승한 부모 + 자녀 수    |
| **Ticket**      | 티켓 번호    | 승객의 티켓 고유 번호        |
| **Fare**        | 요금       | 지불한 승선 요금           |
| **Cabin**       | 객실 번호    | 객실 위치 정보   |
| **Embarked**    | 탑승 항구    | 탑승한 항구 (C, Q, S)    |

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/rngus4656/datasets/refs/heads/main/S2/titanic.csv"

df = pd.read_csv(url)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [2]:
# 데이터의 형태 확인 해당 데이터 테이블은 행 개수, 열 개수
df.shape

(891, 12)

In [3]:
# 데이터 info 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
# 데이터 수치 정보 확인
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## pandas 기본 기능으로 df 살펴보기
> 데이터 조회, 확인 및 선택 방법  

기본 조회 메서드 head, tail, sample  
데이터 프레임의 인덱싱: 라벨 인뎅싱 loc & 정수 인덱싱 iloc

In [6]:
# df의 가장 앞 부분 (디폴트 값 5)
df.head(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [7]:
# df의 가장 뒷 부분
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [14]:
# df의 무작위 샘플
df.sample(10, random_state=42)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
709,710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C
439,440,0,2,"Kvillner, Mr. Johan Henrik Johannesson",male,31.0,0,0,C.A. 18723,10.5000,NaN,S
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C
290,291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S
300,301,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q
333,334,0,3,"Vander Planke, Mr. Leo Edmondus",male,16.0,2,0,345764,18.0000,NaN,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.0,0,0,367231,7.7500,NaN,Q
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S

In [17]:
# 결측치
df.isnull()
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [18]:
# 칼럼별 결측치(isna()=True)의 합
df.isnull().sum()
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [19]:
# 특정 칼럼별 결측치 평균도 구할 수 있다.
df[['Age','Cabin']].isna().mean().round(2) # mean() 평균값, round(n) 소수 n번째까지 반올림

Age      0.20
Cabin    0.77
dtype: float64

In [20]:
# 중복값 점검
df.duplicated().sum()

# 고유값이 포함 된 중복값이 있을때는 df.drop_duplicates()로 제거 해 주는 것이 일반적이다.

np.int64(0)

In [49]:
# 중복값 점검
df.duplicated('Ticket')

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Length: 891, dtype: bool

### 인덱싱과 슬라이싱, 데이터 선택
파이썬의 인덱스는 기본적으로 0부터 시작한다.  
예를 들어, a = ['x', 'y', 'z']의 첫번째 인덱스인 x를 호출하기 위해 0번 인덱스를 조회한다.  
a[0] = 'x', a[1] = 'y', a[2] = 'z' (0번, 1번, 2번 Index 호출)  

* colab(1) 파이썬 기초 - '인덱스 구조' 참고

In [28]:
# 문자열, 리스트 등의 기본 인덱싱

a = ['x', 'y', 'z']
print(a[0])
print(a[1])
print(a[2])

x
y
z

In [36]:
# 슬라이싱의 기본 개념 a[시작:끝 -1] (디폴트값은 전체)

a = ['x', 'y', 'z', '1', '2', '3']
print(a[0:2]) # 0번부터 1번까지 인덱싱
print(a[:3]) # 2번까지 인덱싱
print(a[1:]) #  1번부터 인덱싱
print(a[:]) # 전체 인덱싱
print(a[0::2]) #  1번부터 인덱싱

['x', 'y']
['x', 'y', 'z']
['y', 'z', '1', '2', '3']
['x', 'y', 'z', '1', '2', '3']
['x', 'z', '2']

In [33]:
# 기본 인덱싱 0부터 시작, 슬라이싱은 끝 -1 적용, 데이터 프레임의 기본 축은 axis = 행 0, 열 1

# 칼럼을 선택하는 가장 기본적인 방법
df['PassengerId'] # df.PassengerId 방식으로도 선택할 수 있지만, 코딩 편의상 [] 형식으로 통일.

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64

In [34]:
# 여러 칼럼을 선택할 수도 있다.
df[['PassengerId', 'Sex', 'Age', 'Ticket', 'Fare', 'Survived']]

     PassengerId     Sex   Age            Ticket     Fare  Survived
0              1    male  22.0         A/5 21171   7.2500         0
1              2  female  38.0          PC 17599  71.2833         1
2              3  female  26.0  STON/O2. 3101282   7.9250         1
3              4  female  35.0            113803  53.1000         1
4              5    male  35.0            373450   8.0500         0
..           ...     ...   ...               ...      ...       ...
886          887    male  27.0            211536  13.0000         0
887          888  female  19.0            112053  30.0000         1
888          889  female   NaN        W./C. 6607  23.4500         0
889          890    male  26.0            111369  30.0000         1
890          891    male  32.0            370376   7.7500         0

[891 rows x 6 columns]

#### 라벨 인덱싱 loc, 정수 인덱싱 iloc

라벨 인덱싱: loc[행시작:행끝, 열시작:열끝]을 이용한 인덱싱 (시작: 끝) -> 문자열로 인식하여 인덱싱하는 방식  
정수 인덱싱: iloc[행시작:행끝 -1, 열시작:열끝 -1]을 이용한 인덱싱 (시작:끝 -1) -> 가장 기본적으로 사용되는 방식

In [ ]:
# 데이터 프레임 형식은 df[4:]을 입력하면 오류가 나온다.

In [37]:
# PassengerId를 인덱스로 가진 데이터 프레임의 인덱싱, 슬라이싱
df_a = df[['PassengerId', 'Sex', 'Age', 'Ticket', 'Fare', 'Survived']].set_index('PassengerId', drop=True)
df_a

                Sex   Age            Ticket     Fare  Survived
PassengerId
1              male  22.0         A/5 21171   7.2500         0
2            female  38.0          PC 17599  71.2833         1
3            female  26.0  STON/O2. 3101282   7.9250         1
4            female  35.0            113803  53.1000         1
5              male  35.0            373450   8.0500         0
...             ...   ...               ...      ...       ...
887            male  27.0            211536  13.0000         0
888          female  19.0            112053  30.0000         1
889          female   NaN        W./C. 6607  23.4500         0
890            male  26.0            111369  30.0000         1
891            male  32.0            370376   7.7500         0

[891 rows x 5 columns]

In [66]:
# 라벨 인덱싱을 통한 행과 열 선택

df_a.loc[3:7, 'Ticket':'Survived'] # 해당 라벨을 탐색하여 호출함

                       Ticket     Fare  Survived
PassengerId
3            STON/O2. 3101282   7.9250         1
4                      113803  53.1000         1
5                      373450   8.0500         0
6                      330877   8.4583         0
7                       17463  51.8625         0

In [67]:
df_a.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sex       891 non-null    object
 1   Age       714 non-null    float64
 2   Ticket    891 non-null    object
 3   Fare      891 non-null    float64
 4   Survived  891 non-null    int64
dtypes: float64(2), int64(1), object(2)
memory usage: 74.1+ KB

In [39]:
# 정수 인덱싱을 통한 행과 열 선택

df_a.iloc[2:7, 2:5] # 해당 인덱스를 탐색하여 호출함

                       Ticket     Fare  Survived
PassengerId
3            STON/O2. 3101282   7.9250         1
4                      113803  53.1000         1
5                      373450   8.0500         0
6                      330877   8.4583         0
7                       17463  51.8625         0

#### 불리언(boolean) 인덱싱  
불리언 연산자에 따라 True, False 값으로 분류하여 조회하는 방식  
데이터 프레임 형식으로는 df[df['칼럼'] 불리언 연산자]를 사용한다.

많이 쓰이는 불리언 연산자:
<, >, ==, !=, |, &

In [40]:
# Survived가 1인 데이터 조회
df[df['Survived'] == 1].head() # df[df['Survived'] != 1].head()를 입력하면 반대의 결과가 출력 된다.(== <-> !=)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [41]:
# Fare가 100이상인 데이터 조회
df[df['Fare'] >= 100].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [42]:
# Fare가 100이상인 데이터 조회
df[df['Fare'] >= 100].info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 27 to 856
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  53 non-null     int64
 1   Survived     53 non-null     int64
 2   Pclass       53 non-null     int64
 3   Name         53 non-null     object
 4   Sex          53 non-null     object
 5   Age          48 non-null     float64
 6   SibSp        53 non-null     int64
 7   Parch        53 non-null     int64
 8   Ticket       53 non-null     object
 9   Fare         53 non-null     float64
 10  Cabin        43 non-null     object
 11  Embarked     53 non-null     object
dtypes: float64(2), int64(5), object(5)
memory usage: 5.4+ KB

In [43]:
# Fare가 100이상이거나, Survived가 1인 데이터 (OR 연산자)
df[(df['Fare'] >= 100) | (df['Survived'] == 1)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [44]:
# Fare가 100이상이면서, Survived도 1인 데이터 (AND 연산자)
df[(df['Fare'] >= 100) & (df['Survived'] == 1)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.0,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C

In [45]:
# Fare가 100이상인 데이터 조회
df[df.duplicated('Ticket')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9000,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
117,118,0,2,"Turpin, Mr. William John Robert",male,29.0,1,0,11668,21.0000,NaN,S
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.2750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

# 데이터 조회 및 분석 준비  
원하는 데이터를 조회하고, 용도에 맞게 재구성하며 분석을 준비한다.  
데이터 조건부 조회: 불리언 인덱싱, contains(), (dtype + astype())  
데이터 정렬 및 결측치 처리

## 특정 값 조회  
불리언 인덱싱, contains()를 통해 원하는 값만 조회

In [51]:
# df.str.contains()를 통해 원하는 문자열을 포함하는 데이터만 조회할 수 있다.

# 이름에 Mrs.가 붙은사람 조회
df[df['Name'].str.contains('Mrs.')].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [52]:
# 이름에 Mrs.가 붙고 Survived가 1인 사람 조회을 변수 df_Mrs에 저장
df_Mrs = df[(df['Name'].str.contains('Mrs')) & (df['Survived'] == 1)]
df_Mrs.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [53]:
# df_Mrs의 value_counts 조회 -> 연속형 수치의 경우 유니크값이 너무 많아서 조회하기 힘들다.
df_Mrs.value_counts(subset='Age').head()
df_Mrs['Age'].value_counts().head()

Age
24.0    8
35.0    5
33.0    4
36.0    4
29.0    4
Name: count, dtype: int64

In [54]:
# df_Mrs['Age']의 유니크값, 유니크값 개수 조회
print('Age칼럼의 유니크값:',df_Mrs['Age'].unique())
print('Age칼럼의 유니크값 개수:',df_Mrs['Age'].nunique()) # 개수에서 nan 결측치는 제외한다.

Age칼럼의 유니크값: [38. 35. 27. 14. 55. nan 49. 29. 33. 34. 24. 22. 40. 32. 44. 50. 58. 41.
 19. 17. 36. 31. 60. 28. 42. 45. 23. 63. 54. 48. 39. 53. 52. 18. 30. 51.
 43. 62. 15. 47. 56. 25.]
Age칼럼의 유니크값 개수: 41

## 결측치 중앙값으로 대체하기

In [55]:
# df['Age']의 중앙값 조회
df['Age'].median()

28.0

In [56]:
# Age칼럼의 결측치 개수 확인
df[['Age']].isna().sum()

Age    177
dtype: int64

In [57]:
# sort_values로 재확인
# 총 row 891에서 결측치 177을 제외하면 총 714개의 행이된다. 즉, 714개의 행에다한 중앙값을 계산하면 된다.
(df['Age'].dropna().sort_values(ascending=False).reset_index(drop=True)[356] + df['Age'].dropna().sort_values(ascending=False).reset_index(drop=True)[357]) / 2

np.float64(28.0)

In [58]:
# fillna로 결측치를 중앙값으로 대체
df_2 = df.copy()
df_2['Age'] = df_2['Age'].fillna(df_2['Age'].median())
print(df_2[['Age']].isna().sum())
df_2[['Age']].value_counts(ascending=False, dropna=False)

Age    0
dtype: int64

Age
28.0    202
24.0     30
22.0     27
18.0     26
19.0     25
       ...
53.0      1
66.0      1
70.5      1
74.0      1
80.0      1
Name: count, Length: 88, dtype: int64

중앙값, 평균값, 최빈값 등 하나의 값으로 결측치를 처리한다면, 데이터 분포가 한쪽에 쏠릴 수 있기 때문에  
데이터에 따라, 다양한 코드와 라이브러리를 활용한다.

In [59]:
# 심화 패턴: Age에 가장 영향을 많이 미친 Sex, Pclass 그룹당 median를 구하여 해당 값을 결측치로 대체

df.groupby(['Sex', 'Pclass'])['Age'].median()

Sex     Pclass
female  1         35.0
        2         28.0
        3         21.5
male    1         40.0
        2         30.0
        3         25.0
Name: Age, dtype: float64

In [60]:
# 정답이라고 할 수 있는 방법은 없다. 다양한 기법과 라이브러리들이 있으니 데이터에따라 적절한 접근 방식을 설계 해보는 것이 필요하다.
df_3 = df.copy()
df_3['Age'] = df_3['Age'].fillna(df_3.groupby(['Sex', 'Pclass'])['Age'].transform('median'))
df_3['Age'].value_counts(ascending=False, dropna=False)

Age
25.00    117
21.50     42
30.00     34
40.00     34
24.00     30
        ...
24.50      1
0.67       1
0.42       1
34.50      1
74.00      1
Name: count, Length: 89, dtype: int64

In [61]:
df_3[['Age']].isna().sum()

Age    0
dtype: int64

## 새로운 Feature 생성  
결측치가 있던 행들은 분석시 혼선을 줄 수 있으므로, 새로운 결측치 여부 Feature로 만들어 구분할 수 있다.  
또한, 기존의 Feature를 기반으로 다양한 Feature Engineering을 수행 할 수 있다.

In [64]:
# 결측치가 가장 많은 객실정보 Cabin은 'unknown'으로 대체하고, Embarked는 결측치가 2개이므로 간단하게 최빈값으로 대체한다.

df_3['Cabin'] = df_3['Cabin'].fillna('unknown')
df_3['Embarked'] = df_3['Embarked'].fillna(df_3['Embarked'].mode()[0])

In [65]:
# Age_null 칼럼을 따로 만들어 두어, 결측치 여부를 판단할 수 있게 한다. (0, 1) 이진 분류

df_3['Age_null'] = df['Age'].isna().astype(int)
df_3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_null
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,unknown,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,unknown,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,unknown,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,unknown,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.5,1,2,W./C. 6607,23.4500,unknown,S,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,unknown,Q,0

### 새로운 라벨을 만들어 나이 카테고리 Feature 생성하기  
Age와 같은 중요하면서도 세그먼트가 나뉘는 데이터들은 분석에 따라 연속형 수치가 아닌 범주형으로 보는 것이 더 좋을 수 있다.

In [68]:
# 나이를 구간화, 카테고리화한 변수 지정하기

age_bins = [0, 12, 19, 34, 58, 100]
age_cat = ['Child', 'Teen', 'Young', 'Adult', 'Senior']

print(age_bins, age_cat)

[0, 12, 19, 34, 58, 100] ['Child', 'Teen', 'Young', 'Adult', 'Senior']

In [69]:
# pd.cut으로 라벨링 된 데이터 만들기

AgeGroup = pd.cut(df_3['Age'], bins=age_bins, labels=age_cat)
AgeGroup.head()

0    Young
1    Adult
2    Young
3    Adult
4    Adult
Name: Age, dtype: category
Categories (5, object): ['Child' < 'Teen' < 'Young' < 'Adult' < 'Senior']

In [70]:
# 새로운 Feature인 AgeGroup 추가
df_3['AgeGroup'] = AgeGroup
df_3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_null,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,unknown,S,0,Young
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,unknown,S,0,Young
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,unknown,S,0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,unknown,S,0,Young
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,Teen
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.5,1,2,W./C. 6607,23.4500,unknown,S,1,Young
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,Young
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,unknown,Q,0,Young

# 데이터 정제 및 분석 점검  
몇 가지 핵심적인 정제를 마친 df_3로 어떤 분석을 할 수 있는지 연습 해보기

In [76]:
# 이름에 Mrs.를 포함하면서 생존한 사람 조회

df_3_Mrs = df_3[(df_3['Name'].str.contains('Mrs') & df_3['Survived'] == 1)].reset_index(drop=True)
df_3_Mrs.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_null,AgeGroup
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,Adult
1,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,Adult
2,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,unknown,S,0,Young
3,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,unknown,C,0,Teen
4,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,unknown,S,0,Adult

In [80]:
# 생존한 기혼 여성은 대부분 Adult, Young 그룹에 속해있다.
df_3_Mrs[['AgeGroup']].value_counts()

AgeGroup
Adult       50
Young       40
Teen         9
Senior       3
Child        0
Name: count, dtype: int64

In [81]:
# 전체 연령 그룹을 확인했을때, 청년, 성인그룹이 가장 많이 분포되어 있다.
df_3['AgeGroup'].value_counts()

AgeGroup
Young     461
Adult     238
Teen       95
Child      69
Senior     28
Name: count, dtype: int64

In [82]:
# 객실 등급은 3등석이 가장 많았고, 2등석이 제일 적었다.
df_3['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [84]:
# 결측치가 많았던 Age, 영향 있었을까?
df_3.groupby("Age_null")["Survived"].mean()

Age_null
0    0.406162
1    0.293785
Name: Survived, dtype: float64

In [95]:
# 생존한 객실 등급 그룹은 높을수록 생존율이 좋았다.
df_3.groupby("Pclass")["Survived"].mean().round(2)

Pclass
1    0.63
2    0.47
3    0.24
Name: Survived, dtype: float64

In [96]:
# 생존한 성별 그룹을 볼 때, 성별은 여성 우선, 남성은 아이 우선으로 살리려고 한 것을 유추할 수 있다.
df_3.groupby(["Sex","AgeGroup"])["Survived"].mean().round(2)

/tmp/ipython-input-2062168476.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_3.groupby(["Sex","AgeGroup"])["Survived"].mean().round(2)

Sex     AgeGroup
female  Child       0.59
        Teen        0.79
        Young       0.71
        Adult       0.81
        Senior      1.00
male    Child       0.57
        Teen        0.10
        Young       0.16
        Adult       0.20
        Senior      0.12
Name: Survived, dtype: float64

In [99]:
# 객실 등급이 높을수록 전체적인 생존율이 높고, 나이가 적은 그룹이 우선적으로 생존된 걸 확인할 수 있다.
df_3.groupby(["Sex", "Pclass", "AgeGroup"])["Survived"].mean().round(2)

/tmp/ipython-input-262432130.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_3.groupby(["Sex", "Pclass", "AgeGroup"])["Survived"].mean().round(2)

Sex     Pclass  AgeGroup
female  1       Child       0.00
                Teen        1.00
                Young       0.96
                Adult       0.98
                Senior      1.00
        2       Child       1.00
                Teen        1.00
                Young       0.92
                Adult       0.86
                Senior       NaN
        3       Child       0.48
                Teen        0.59
                Young       0.53
                Adult       0.20
                Senior      1.00
male    1       Child       1.00
                Teen        0.25
                Young       0.48
                Adult       0.36
                Senior      0.14
        2       Child       1.00
                Teen        0.10
                Young       0.09
                Adult       0.04
                Senior      0.20
        3       Child       0.36
                Teen        0.08
                Young       0.14
                Adult       0.06
                Senior      0.00
Name: Survived, dtype: float64

In [98]:
# 단순 비율뿐만 아니라, 승객 인원수에 따른 생존율과 평균적인 객실 요금 확인이 가능하다.
df_3.groupby(["Sex", "Pclass"]).agg(cnt_Id=("PassengerId", "count"),avg_survived=("Survived", "mean"),avg_fare=("Fare", "mean")).round(2)

               cnt_Id  avg_survived  avg_fare
Sex    Pclass
female 1           94          0.97    106.13
       2           76          0.92     21.97
       3          144          0.50     16.12
male   1          122          0.37     67.23
       2          108          0.16     19.74
       3          347          0.14     12.66

# 연습 예제

1. 어떤 AgeGroup이 가장 생존률이 높았고, 생존자 수가 가장 많은 그룹은 어디였을까?  

<details>
<summary> Hint code </summary>  



```
print('[전체 인원]\n', df_3.groupby(['AgeGroup'])[['Survived']].count().sort_values(by='Survived', ascending=False),
      '\n[생존자수]\n', df_3.groupby(['AgeGroup'])[['Survived']].sum().sort_values(by='Survived', ascending=False),
      '\n[생존율]\n', df_3.groupby(['AgeGroup'])[['Survived']].mean().sort_values(by='Survived', ascending=False).round(2))
```

```
df_3.groupby(['AgeGroup']).agg(cnt_group = ('AgeGroup', 'count'), cnt_survived = ('Survived', 'sum'), avg_survived =('Survived', 'mean')).round(2)
```
</details>

In [94]:

print(df_3['AgeGroup'].value_counts(ascending=False).head(1),df_3['AgeGroup'].value_counts(ascending=False).tail(1))
df_4 = df_3[(df_3['Survived'] == 1)]
print(df_4['AgeGroup'].value_counts(ascending=False).head(1),df_4['AgeGroup'].value_counts(ascending=False).tail(1))

AgeGroup
Young    461
Name: count, dtype: int64 AgeGroup
Senior    28
Name: count, dtype: int64
AgeGroup
Young    155
Name: count, dtype: int64 AgeGroup
Senior    7
Name: count, dtype: int64

2. 성별과 객실 등급 중 어떤 특성이 생존에 미치는 영향이 강해보이는가?

*성별과 객실 등급 각각 따로 확인, 정답은 없으니 자유롭게 분석 해보기*

<details>
<summary> Hint code </summary>  

```
df_3.groupby('Sex').agg(cnt=('Sex', 'count'), mean=('Survived', 'mean')).round(2)
```  

```
df_3.groupby('Pclass').agg(cnt=('Pclass', 'count'), mean=('Survived', 'mean')).round(2)
```  

</details>

In [ ]:
# 성별 특성 분석
df_3.groupby(["Sex", "Pclass", "AgeGroup"])["Survived"].mean().round(2)

In [ ]:
# 객실 등급 특성 분석

**심화**
 1. 데이터 Feature를 더 추가한다면, 어떤 특성을 추가할 수 있는가?

2. 다른 데이터 셋으로도 비슷한 분석이 가능한가?  
<details>
<summary>iris 데이터 셋</summary>

```
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/rngus4656/datasets/refs/heads/main/S2/iris.csv")
df.head()
```

</details>